version: "3.9"
services:
  postgresql:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=social_network_app
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=social_network
  springboot-app:
    container_name: social-network-app
    image: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgresql