version: "3.9"
services:
  postgresql:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=social_network_app
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=social_network
      - PGDATA=/data/postgres
    networks:
      - social-network-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - social-network-network
    restart: unless-stopped

  springboot-app:
    container_name: social-network-app
    image: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/social_network?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: social_network_app
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgresql
    networks:
      - social-network-network

networks:
  social-network-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: